# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello_world.proto',
  package='proto_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11hello_world.proto\x12\x0eproto_messages\"3\n\nHelloWorld\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0b\n\x03msg\x18\x03 \x01(\tb\x06proto3'
)




_HELLOWORLD = _descriptor.Descriptor(
  name='HelloWorld',
  full_name='proto_messages.HelloWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto_messages.HelloWorld.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='proto_messages.HelloWorld.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='proto_messages.HelloWorld.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['HelloWorld'] = _HELLOWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloWorld = _reflection.GeneratedProtocolMessageType('HelloWorld', (_message.Message,), {
  'DESCRIPTOR' : _HELLOWORLD,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:proto_messages.HelloWorld)
  })
_sym_db.RegisterMessage(HelloWorld)


# @@protoc_insertion_point(module_scope)
